### PR TITLE
Fix deep nesting in CEF-X Mass Summaries

### PR DESCRIPTION
**Pull request by ghost**
- Updated TreeTraverser in https://github.com/virtualsatellite/VirtualSatellite4-Core/issues/414 (Still needs a PR).
- Added TreeTaverser to Summary View and used it for TableContentProvider and for the Pie Chart Data Collection.
- Also removed several warnings.

### CODE REVIEW

**Comment by PhilMFischer** [comment]
Depends on https://github.com/virtualsatellite/VirtualSatellite4-CEF/pull/64

**Review by SaMuellerDLR — CHANGES_REQUESTED** [review]
The changes on the migrators, concepts, etc. confuse me.
I think the changes should really be just in the masssummary related classes.

**Comment by PhilMFischer** [comment]
> The changes on the migrators, concepts, etc. confuse me.
> I think the changes should really be just in the masssummary related classes.

The reason for the changes in the migrators is that, there were some old never used migrators from the copy and paste of the plugin.

Basically it were sourcefiles that had absolutely no relevance. Same story for the documentation snippet.

Therefore i deleted them.

**Review by SaMuellerDLR — APPROVED** [review]
Approved!

**Review by andriikovalov-dlr — APPROVED** [review]

**Pull request merged**
