### PR TITLE
Add simple UI to show Overwrite-Falg in SEI-Editor

### PR DESCRIPTION
**Pull request by franzTobiasDLR**
Show Override-State in SEI-Editor.

Requiers following small change in core:
https://github.com/virtualsatellite/VirtualSatellite4-Core/commit/8327baa96aaa0e1d01776131ced493dce0e94562

grafik

Editor:
Untitled
For calculated properties, editor cannot be opened...

### CODE REVIEW

**Comment by franzTobiasDLR** [comment]
Should work after this action completed and deployed on core-integration:
https://github.com/virtualsatellite/VirtualSatellite4-Core/commit/8327baa96aaa0e1d01776131ced493dce0e94562

**Comment by franzTobiasDLR** [comment]
I updated the UI so that the column is the most right column to not disturb engineers and added the hint "<<calculated>>" if the property is calculated. The "<<>>" should make clear that this is not an actuall value of override...

Do you have opinions on that? @dellerDLR @pchrszon-dlr 

grafik

**Comment by pchrszon-dlr** [comment]
I like the idea of having the calculated icons in the Value column. Sure, the alignment of the numbers is off, but I don't mind it that much. I don't know if this is possible, but it might help to have the numbers in the Value column aligned on the right, instead of on the left.

Regarding the icons in the Override column: I immediately understood the one for 'false', but I would have to guess what the 'true' one means. Is it a crossed-out link?

Maybe the Override column would be easier to understand, if the possible entries would be "inherited", "overridden", and "calculated". For "true" and "false", you always have to read the entries with respect to the column header, which is (at least for me) not as intuitive.

**Review by pchrszon-dlr — APPROVED** [review]

**Comment by franzTobiasDLR** [comment]
Here another UI Option: This way values are alligned again, but now it might be less clear again that some numbers are calculated and cannot be edited...

Any opinons?

grafik

**Comment by pchrszon-dlr** [comment]
I like the last option better than the previous one. It is somewhat similar to what we had before (with the icons in the Name column), but now the icons are closer to the actual values. I think in connection with the Override column, which explicitly states that some values are calculated, it is quite clear (to me) what can be edited and what can't be.

**Comment by franzTobiasDLR** [comment]
Latest version:
-> I added the icons on names again, otherwise it looks weird if we add a mode specific value. THe vales now have the float icon:
grafik

**Comment by dellerDLR** [comment]
I think I also prefer to have the icons on the value column.
I prefer the latest version, here it is clear to me what is overridden and what is not.

**Review by dellerDLR — APPROVED** [review]

**Comment by dellerDLR** [comment]
What about systemmodes?
You can decide on a per system mode basis if you inherit the value or override it, right?
image

**Comment by franzTobiasDLR** [comment]
What do you think of grey font for calculated parameters?

grafik

**Comment by pchrszon-dlr** [comment]
That looks quite nice! I think it would also be an option to use the grey foreground for inherited values instead of calculated values. But this depends on which property (inheritance/calculated) we want to emphasize.

**Comment by franzTobiasDLR** [comment]
> That looks quite nice! I think it would also be an option to use the grey foreground for inherited values instead of calculated values. But this depends on which property (inheritance/calculated) we want to emphasize.

I actually prefer calculated as the color somewhat implies that the row is 'disabled' and thus read-only. Which is not the case for inherited values.

**Comment by pchrszon-dlr** [comment]
Yes, that's true. It would be fine with me to use the grey color for the calculated values then.

**Comment by franzTobiasDLR** [comment]
Last version for today: now with system mode support:

**Comment by franzTobiasDLR** [comment]
@dellerDLR @pchrszon-dlr  I'm done with this PR now. 

Did some code quality improvements and now made sure that mode parameters can only be edited if it makes sense (before you could always change them). Also make sure mode parameters are highlighted correctly (override / inherited / calculated) and for that implemented a method that evaluates if mode values are calculated or not... 

Do you want to have another look at this PR?

**Comment by pchrszon-dlr** [comment]
I checked the two recent commits and see no issues. You still have my approval.

**Comment by dellerDLR** [comment]
I tested the UI and everything seems to work

**Pull request merged**
